language: java
jdk:
- oraclejdk8
before_script:
  - export MAVEN_OPTS="-Xmx4096m -Xms1024 -Xss64m -server"
env:
  - GROUP=1s
  - GROUP=10s
  - GROUP=1m
  - GROUP=10m
  - GROUP="correctness.*"
  - GROUP="consistency.*"
script: travis_wait mvn clean install -DtestFailureIgnore=true -Dgroups=$GROUP
branches:
  only:
    - develop
    - /^feature.*$/
notifications:
  recipients:
    - choco@emn.fr
  on_success: always
  on_failure: always

