language: java
jdk:
- oraclejdk8
before_script:
  - "export MAVEN_OPTS='-Xmx4096m -Xms1024 -Xss64m -server'"
env:
  - GROUP=1s,10s
  - GROUP=1m,10m
  - GROUP=30m
script: travis_wait mvn clean install -DtestFailureIgnore=true -Dgroups=$GROUP
branches:
  only:
    - develop
notifications:
  recipients:
    - choco@emn.fr
  on_success: always
  on_failure: always

