language: java
jdk:
- oraclejdk8
before_script:
  - "export MAVEN_OPTS='-Xmx4096m -Xms1024 -Xss64m -server'"
script: travis_wait ./src/scripts/build.sh
branches:
  only:
    - develop
    - release
notifications:
  recipients:
    - choco@emn.fr
  on_success: always
  on_failure: always

